import { createContext, useCallback, useContext, useEffect, useMemo, useReducer, useState, type ReactNode } from 'react';
import { v4 as uuidv4 } from 'uuid';
import { findNextHoliday, getHolidaysList } from '@/domain/holidays';
import {
  getTimerType,
  parseTimer,
  type Holiday,
  type Timer,
  type TimerType,
  type TimeValue,
} from '@/domain/timer';
import { timerReducer, type TimerState } from '@/features/timer-management/reducer';
import { addNotification, removeNotification } from '@/services/notificationManager';
import { loadSyncPayload, saveSyncPayload } from '@/services/sync';
import { readTimers, writeTimers } from '@/services/storage';

export type TimerInput = {
  id?: string;
  name: string;
  type?: TimerType;
  targetDate?: TimeValue;
  timezone?: string;
  startTime?: TimeValue | null;
  isRunning?: boolean;
  pausedAt?: TimeValue | null;
  totalPausedTime?: number;
  laps?: unknown[];
  color?: string;
  createdAt?: string;
  isAutoGenerated?: boolean;
  [key: string]: unknown;
};

export type TimerUpdate = Partial<Timer> & Record<string, unknown>;

export interface TimerContextValue {
  timers: Timer[];
  activeTimerId: string | null;
  setActiveTimerId: (id: string | null) => void;
  reorderTimers: (orderedIds: string[]) => void;
  addTimer: (timerData: TimerInput) => string;
  deleteTimer: (id: string) => void;
  updateTimer: (id: string, updatedData: TimerUpdate) => void;
  renameStopwatchLap: (timerId: string, lapIndex: number, name: string) => void;
  deleteStopwatchLap: (timerId: string, lapIndex: number) => void;
  getActiveTimer: () => Timer | null;
  holidaysList: Holiday[];
  checkAndUpdateDefaultTimer: () => void;
}

const TimerContext = createContext<TimerContextValue | null>(null);

function getDefaultTimer(): Timer {
  const nextHoliday = findNextHoliday();
  return {
    id: 'default',
    name: nextHoliday.name,
    targetDate: nextHoliday.date,
    timezone: Intl.DateTimeFormat().resolvedOptions().timeZone,
    color: nextHoliday.color,
    createdAt: new Date().toISOString(),
    isAutoGenerated: true,
  };
}

function isCountdown(timer: Timer): boolean {
  return getTimerType(timer) === 'countdown';
}

function toNotification(timer: Timer): { id: string; title: string; targetTime: number } | null {
  if (!isCountdown(timer) || !('targetDate' in timer)) return null;
  const targetDate = (timer as Timer & { targetDate: TimeValue }).targetDate;
  const targetTime = targetDate instanceof Date
    ? targetDate.getTime()
    : typeof targetDate === 'number'
      ? targetDate
      : new Date(targetDate).getTime();
  return { id: timer.id, title: timer.name, targetTime };
}

function parseTimerInput(timerData: TimerInput): Timer {
  const parsed = parseTimer({
    ...timerData,
    id: timerData.id || uuidv4(),
    createdAt: timerData.createdAt || new Date().toISOString(),
    isAutoGenerated: timerData.isAutoGenerated === true,
    type: timerData.type || 'countdown',
  });
  if (!parsed) throw new Error('计时器数据格式错误');
  return parsed;
}

export function TimerProvider({ children }: { children: ReactNode }) {
  const [state, dispatch] = useReducer(timerReducer, { timers: [], activeTimerId: null } satisfies TimerState);
  const { timers, activeTimerId } = state;
  const [isLoaded, setIsLoaded] = useState(false);
  const [isSyncing, setIsSyncing] = useState(false);
  const [holidaysList, setHolidaysList] = useState<Holiday[]>([]);

  console.log(`TimePulse 应用启动 - ${new Date().toLocaleString()}`);

  useEffect(() => {
    setHolidaysList(getHolidaysList());
  }, []);

  useEffect(() => {
    console.log(`${new Date().toLocaleTimeString()} | [初始化] 开始加载计时器数据`);
    const loadedTimers = readTimers();
    const savedActiveTimerId = localStorage.getItem('activeTimerId');
    console.log(`${new Date().toLocaleTimeString()} | [本地存储] 找到 ${loadedTimers.length} 个本地计时器`);
    console.log(`${new Date().toLocaleTimeString()} | [本地存储] 上次活动计时器ID: ${savedActiveTimerId || '未设置'}`);

    if (loadedTimers.length === 0) {
      const defaultTimer = getDefaultTimer();
      dispatch({ type: 'replace', timers: [defaultTimer], activeTimerId: defaultTimer.id });
      console.log(`${new Date().toLocaleTimeString()} | [初始化] 没有本地计时器，创建默认计时器`);
    } else {
      const selectedId = savedActiveTimerId && loadedTimers.some((timer) => timer.id === savedActiveTimerId)
        ? savedActiveTimerId
        : loadedTimers[0].id;
      dispatch({ type: 'replace', timers: loadedTimers, activeTimerId: selectedId });
      console.log(`${new Date().toLocaleTimeString()} | [初始化] 恢复活动计时器: ${selectedId}`);
    }
    setIsLoaded(true);
    console.log(`${new Date().toLocaleTimeString()} | [初始化] 本地数据加载完成，共${loadedTimers.length || 1}个计时器`);

    const syncData = async () => {
      const syncId = localStorage.getItem('timepulse_sync_id');
      const syncPass = localStorage.getItem('timepulse_sync_password');
      if (!syncId || !syncPass) {
        console.log(`${new Date().toLocaleTimeString()} | [云端同步] 未配置同步信息，跳过远程同步`);
        return;
      }
      try {
        setIsSyncing(true);
        console.log(`${new Date().toLocaleTimeString()} | [云端同步] 检测到同步配置，开始从远程加载数据`);
        const remoteData = await loadSyncPayload(syncId, syncPass);
        if (remoteData.timers.length > 0) {
          dispatch({ type: 'replace', timers: remoteData.timers, activeTimerId: remoteData.activeTimerId });
          writeTimers(remoteData.timers);
          if (remoteData.activeTimerId) localStorage.setItem('activeTimerId', remoteData.activeTimerId);
          console.log(`${new Date().toLocaleTimeString()} | [云端同步] 已成功从远程同步 ${remoteData.timers.length} 个计时器到本地`);
        } else {
          console.log(`${new Date().toLocaleTimeString()} | [云端同步] 远程数据为空或无效，继续使用本地数据`);
        }
      } catch (error) {
        console.error(`${new Date().toLocaleTimeString()} | [云端同步] 从远程同步数据失败:`, error);
      } finally {
        setIsSyncing(false);
        console.log(`${new Date().toLocaleTimeString()} | [云端同步] 远程同步操作完成`);
      }
    };
    void syncData();
  }, []);

  useEffect(() => {
    if (!isLoaded || !activeTimerId) return;
    localStorage.setItem('activeTimerId', activeTimerId);
    const activeTimer = timers.find((timer) => timer.id === activeTimerId);
    if (activeTimer) console.log(`${new Date().toLocaleTimeString()} | [本地存储] 活动计时器名称: ${activeTimer.name}`);
  }, [activeTimerId, isLoaded, timers]);

  useEffect(() => {
    if (!isLoaded || timers.length === 0) return;
    writeTimers(timers);
    const syncId = localStorage.getItem('timepulse_sync_id');
    const syncPass = localStorage.getItem('timepulse_sync_password');
    if (!syncId || !syncPass || isSyncing) return;
    const syncToRemote = window.setTimeout(() => {
      void saveSyncPayload(syncId, syncPass, { timers, activeTimerId }).catch((error: unknown) => {
        console.error(`${new Date().toLocaleTimeString()} | [云端同步] 自动同步到云端失败:`, error);
      });
    }, 500);
    return () => window.clearTimeout(syncToRemote);
  }, [timers, activeTimerId, isLoaded, isSyncing]);

  const checkAndUpdateDefaultTimer = useCallback(() => {
    const defaultTimer = timers.find((timer) => timer.isAutoGenerated === true);
    if (!defaultTimer || !('targetDate' in defaultTimer)) return;
    const targetDate = (defaultTimer as Timer & { targetDate: TimeValue }).targetDate;
    const targetTime = targetDate instanceof Date
      ? targetDate.getTime()
      : typeof targetDate === 'number'
        ? targetDate
        : new Date(targetDate).getTime();
    if (targetTime > Date.now()) return;
    const newDefaultTimer = getDefaultTimer();
    dispatch({ type: 'replace', timers: [newDefaultTimer, ...timers.filter((timer) => timer.id !== defaultTimer.id)], activeTimerId: activeTimerId === defaultTimer.id ? newDefaultTimer.id : activeTimerId });
    console.log(`${new Date().toLocaleTimeString()} | [计时器管理] 默认计时器 ${defaultTimer.name} 已过期，已替换为 ${newDefaultTimer.name}`);
  }, [activeTimerId, timers]);

  useEffect(() => {
    if (!isLoaded || timers.length === 0) return;
    const intervalId = window.setInterval(checkAndUpdateDefaultTimer, 60 * 1000);
    checkAndUpdateDefaultTimer();
    return () => window.clearInterval(intervalId);
  }, [checkAndUpdateDefaultTimer, isLoaded, timers.length]);

  const setActiveTimerId = useCallback((id: string | null) => {
    if (id) dispatch({ type: 'select', id });
  }, []);

  const reorderTimers = useCallback((orderedIds: string[]) => {
    dispatch({ type: 'reorder', ids: orderedIds });
  }, []);

  const addTimer = useCallback((timerData: TimerInput): string => {
    const newTimer = parseTimerInput(timerData);
    dispatch({ type: 'upsert', timer: newTimer });
    const notification = toNotification(newTimer);
    if (notification) void addNotification(notification).catch((error: unknown) => console.log('设置通知失败:', error));
    console.log(`${new Date().toLocaleTimeString()} | [计时器管理] 已添加计时器: ${newTimer.name} (${getTimerType(newTimer)})`);
    return newTimer.id;
  }, []);

  const deleteTimer = useCallback((id: string) => {
    removeNotification(id);
    const remaining = timers.filter((timer) => timer.id !== id);
    const replacement = remaining.length === 0 ? getDefaultTimer() : undefined;
    dispatch({ type: 'remove', id, replacement });
    console.log(`${new Date().toLocaleTimeString()} | [计时器管理] 已删除计时器ID: ${id}`);
  }, [timers]);

  const updateTimer = useCallback((id: string, updatedData: TimerUpdate) => {
    const current = timers.find((timer) => timer.id === id);
    if (!current) return;
    const updatedTimer = parseTimer({ ...current, ...updatedData, id });
    if (!updatedTimer) return;
    dispatch({ type: 'update', timer: updatedTimer });
    const notification = toNotification(updatedTimer);
    if (notification) void addNotification(notification).catch((error: unknown) => console.log('更新通知失败:', error));
    console.log(`${new Date().toLocaleTimeString()} | [计时器管理] 已更新计时器ID: ${id}`);
  }, [timers]);

  const renameStopwatchLap = useCallback((timerId: string, lapIndex: number, name: string) => {
    dispatch({ type: 'renameStopwatchLap', timerId, lapIndex, name });
  }, []);

  const deleteStopwatchLap = useCallback((timerId: string, lapIndex: number) => {
    dispatch({ type: 'deleteStopwatchLap', timerId, lapIndex });
  }, []);

  const getActiveTimer = useCallback(() => timers.find((timer) => timer.id === activeTimerId) ?? null, [activeTimerId, timers]);

  const value = useMemo<TimerContextValue>(() => ({
    timers,
    activeTimerId,
    setActiveTimerId,
    reorderTimers,
    addTimer,
    deleteTimer,
    updateTimer,
    renameStopwatchLap,
    deleteStopwatchLap,
    getActiveTimer,
    holidaysList,
    checkAndUpdateDefaultTimer,
  }), [activeTimerId, addTimer, checkAndUpdateDefaultTimer, deleteTimer, deleteStopwatchLap, getActiveTimer, holidaysList, renameStopwatchLap, reorderTimers, setActiveTimerId, timers, updateTimer]);

  return <TimerContext.Provider value={value}>{children}</TimerContext.Provider>;
}

export function useTimers(): TimerContextValue {
  const context = useContext(TimerContext);
  if (!context) throw new Error('useTimers must be used within TimerProvider');
  return context;
}

export default TimerContext;
