/**
 * Stable timer contract shared by storage, sharing, sync and UI adapters.
 * Unknown properties are intentionally retained when data crosses a boundary;
 * old releases may have fields that newer releases do not understand yet.
 */
export type TimerType = 'countdown' | 'stopwatch' | 'worldclock';

export type TimeValue = number | string | Date;

export interface Lap {
  id?: string;
  name?: string;
  time?: number;
  total?: number;
  elapsedMs?: number;
  timestamp?: string;
  createdAt?: string;
  [key: string]: unknown;
}

export interface BaseTimer {
  id: string;
  name: string;
  type?: TimerType;
  color?: string;
  createdAt?: string;
  isAutoGenerated?: boolean;
  [key: string]: unknown;
}

export interface CountdownTimer extends BaseTimer {
  type?: 'countdown';
  targetDate: TimeValue;
  timezone: string;
}

export interface StopwatchTimer extends BaseTimer {
  type: 'stopwatch';
  startTime: TimeValue | null;
  isRunning: boolean;
  pausedAt?: TimeValue | null;
  totalPausedTime: number;
  laps: Lap[];
}

export interface WorldClockTimer extends BaseTimer {
  type: 'worldclock';
  timezone: string;
  city: string;
  country: string;
}

export type Timer = CountdownTimer | StopwatchTimer | WorldClockTimer;

export interface SyncPayload {
  timers: Timer[];
  activeTimerId: string | null;
}

export interface Holiday {
  name: string;
  date: string;
  color: string;
  [key: string]: unknown;
}

export function getTimerType(timer: Partial<BaseTimer>): TimerType {
  return timer.type === 'stopwatch' || timer.type === 'worldclock'
    ? timer.type
    : 'countdown';
}

export function isCountdownTimer(timer: BaseTimer): timer is CountdownTimer {
  return getTimerType(timer) === 'countdown';
}

export function isStopwatchTimer(timer: BaseTimer): timer is StopwatchTimer {
  return timer.type === 'stopwatch';
}

export function isWorldClockTimer(timer: BaseTimer): timer is WorldClockTimer {
  return timer.type === 'worldclock';
}

function asRecord(value: unknown): Record<string, unknown> | null {
  return typeof value === 'object' && value !== null ? value as Record<string, unknown> : null;
}

export function parseTimer(value: unknown): Timer | null {
  const record = asRecord(value);
  if (!record || typeof record.id !== 'string' || typeof record.name !== 'string') {
    return null;
  }

  const type = getTimerType(record as Partial<BaseTimer>);
  if (type === 'stopwatch') {
    return {
      ...record,
      type,
      startTime: (record.startTime as TimeValue | null | undefined) ?? null,
      isRunning: record.isRunning === true,
      pausedAt: (record.pausedAt as TimeValue | null | undefined) ?? null,
      totalPausedTime: typeof record.totalPausedTime === 'number' ? record.totalPausedTime : 0,
      laps: Array.isArray(record.laps) ? record.laps.filter((lap): lap is Lap => Boolean(asRecord(lap))) : [],
    } as StopwatchTimer;
  }

  if (type === 'worldclock') {
    return {
      ...record,
      type,
      timezone: typeof record.timezone === 'string' ? record.timezone : 'UTC',
      city: typeof record.city === 'string' ? record.city : '',
      country: typeof record.country === 'string' ? record.country : '',
    } as WorldClockTimer;
  }

  return {
    ...record,
    type: record.type === 'countdown' ? 'countdown' : undefined,
    targetDate: (record.targetDate as TimeValue | undefined) ?? new Date().toISOString(),
    timezone: typeof record.timezone === 'string'
      ? record.timezone
      : Intl.DateTimeFormat().resolvedOptions().timeZone,
  } as CountdownTimer;
}

export function parseTimers(value: unknown): Timer[] {
  if (!Array.isArray(value)) return [];
  return value.map(parseTimer).filter((timer): timer is Timer => timer !== null);
}

export function parseSyncPayload(value: unknown): SyncPayload | null {
  const record = asRecord(value);
  if (!record) return null;
  const timers = parseTimers(record.timers);
  const activeTimerId = typeof record.activeTimerId === 'string' ? record.activeTimerId : null;
  return { timers, activeTimerId };
}

export function toTimestamp(value: TimeValue | null | undefined): number {
  if (value instanceof Date) return value.getTime();
  if (typeof value === 'number') return value;
  if (typeof value === 'string') return new Date(value).getTime();
  return Number.NaN;
}
